// Source data for the Pro-lab scenario bank (server-side only — never shipped
// to the client). Migrated verbatim from the inline app.js `questions` array.
export default [
  { title: "Boundaries — Define planning and action boundaries", primary_domain: 1, objective: "Define planning and action boundaries", difficulty: null,
    prompt: "A coding agent receives an issue and immediately edits the default branch before a maintainer sees its approach. The team wants speed but must prevent unreviewed architectural changes. What is the best first control?",
    artifact_type: "code", artifact_content: JSON.stringify({ name: "agent-policy.yml", code: "mode: autonomous\nplan:\n  output: false\n  approval_before_action: false\nexecution:\n  target_branch: main" }),
    options: ["Require the agent to output a structured plan and block execution until that plan is approved", "Shorten the issue template so the agent starts faster", "Give the agent a larger context window", "Run the same agent twice and compare the commits"],
    correct_index: 0, correct_explanation: "Separating planning from execution creates a meaningful review gate before action. The plan must be structured and validated; more context or duplicate runs do not prevent an unsafe edit." },
  { title: "Boundaries — Define measurable success criteria", primary_domain: 1, objective: "Define measurable success criteria", difficulty: null,
    prompt: "An agent closes dependency-update issues whenever the build passes, but some releases still break at runtime. Which task definition most improves its success criteria?",
    artifact_type: null, artifact_content: null,
    options: ["Success means the pull request was created", "Success means CI, targeted integration tests, and the deployment smoke check all pass", "Success means the agent used fewer than ten tool calls", "Success means a reviewer reacted with an emoji"],
    correct_index: 1, correct_explanation: "Success criteria should reflect the development intent and operational outcome. A build alone is an incomplete proxy when runtime behavior matters." },
  { title: "Boundaries — Produce inspectable artifacts", primary_domain: 1, objective: "Produce inspectable artifacts", difficulty: null,
    prompt: "A security team cannot reconstruct why an autonomous refactor changed an authorization rule. Which workflow change gives the strongest observability without stopping automation?",
    artifact_type: null, artifact_content: null,
    options: ["Record the agent's plan, tool calls, diffs, test results, and approval in the pull request", "Ask the agent to explain itself only if a bug is reported", "Save the final chat transcript on a developer laptop", "Disable autonomous refactoring entirely"],
    correct_index: 0, correct_explanation: "Standard development artifacts—especially the pull request—should carry the plan, evidence, changes, and approval so the action remains inspectable and auditable." },
  { title: "Tool use — Configure least-privilege tool access", primary_domain: 2, objective: "Configure least-privilege tool access", difficulty: null,
    prompt: "A documentation agent only needs to read source files and open pull requests, but its MCP token can administer repositories. What should you do?",
    artifact_type: "code", artifact_content: JSON.stringify({ name: "mcp.json", code: "{\n  \"repositories\": [\"*\"],\n  \"permissions\": [\"repo:admin\", \"org:admin\"],\n  \"allowed_actions\": [\"read\", \"pull_request\"]\n}" }),
    options: ["Keep admin access because the agent is trusted", "Scope the token to required repositories and only the read-content/create-PR permissions", "Hide the token value in the system prompt", "Add a second admin token for failover"],
    correct_index: 1, correct_explanation: "Tool permissions should be scoped to the minimum actions and repositories required. Secret placement does not compensate for excessive authorization." },
  { title: "Tool use — Implement safe retries", primary_domain: 2, objective: "Implement safe retries", difficulty: null,
    prompt: "A deployment tool times out after sending a release request. The agent retries and occasionally creates two releases. What should the workflow implement first?",
    artifact_type: null, artifact_content: null,
    options: ["A higher retry limit", "An idempotency key plus state verification before retrying", "A larger model", "A second deployment agent"],
    correct_index: 1, correct_explanation: "When the outcome is uncertain, retrying blindly is unsafe. Idempotency and state verification make repeated calls deterministic and prevent duplicate side effects." },
  { title: "Tool use — Scope execution environment", primary_domain: 2, objective: "Scope execution environment", difficulty: null,
    prompt: "An agent must fix a bug in one repository but its credentials can create branches across the entire organization. Which setup best contains the blast radius?",
    artifact_type: null, artifact_content: null,
    options: ["Repository-scoped credentials, an isolated branch, and a pull-request-only path", "Organization admin access with detailed logging", "A global token that expires in one year", "Direct pushes with branch names prefixed by agent/"],
    correct_index: 0, correct_explanation: "Repository scope, branch isolation, and a reviewed PR path constrain both permission and execution context. Naming conventions and logging alone do not reduce authority." },
  { title: "Memory — Choose an appropriate memory strategy", primary_domain: 3, objective: "Choose an appropriate memory strategy", difficulty: null,
    prompt: "A triage agent must remember a customer's approved exception for 90 days across sessions, but unrelated customers must never influence each other. Which design fits?",
    artifact_type: "code", artifact_content: JSON.stringify({ name: "memory-record.json", code: "{\n  \"customer\": \"acme-42\",\n  \"fact\": \"Approved exception\",\n  \"scope\": \"global\",\n  \"expires_at\": null\n}" }),
    options: ["Keep all conversations in one long prompt", "Use external, customer-scoped memory with an expiration rule", "Store the exception in the model's system prompt", "Rely on short-term conversation memory"],
    correct_index: 1, correct_explanation: "The fact must persist across sessions, so short-term memory is insufficient. External memory should be scoped per customer and expire with the policy." },
  { title: "Memory — Resume from durable state", primary_domain: 3, objective: "Resume from durable state", difficulty: null,
    prompt: "A long-running migration agent crashes after completing 73 of 100 repositories. How should it resume safely?",
    artifact_type: null, artifact_content: null,
    options: ["Restart from repository one to verify everything", "Load a durable checkpoint of completed work and verify the next pending repository", "Ask the model to remember where it stopped", "Infer progress from the current chat length"],
    correct_index: 1, correct_explanation: "Durable checkpoints preserve progress and decisions outside transient context. Verification before the next action limits drift and repeated work." },
  { title: "Memory — Prevent stale context", primary_domain: 3, objective: "Prevent stale context", difficulty: null,
    prompt: "An agent keeps recommending a retired deployment procedure because it remains in long-term memory. What is the best memory control?",
    artifact_type: null, artifact_content: null,
    options: ["Increase retrieval top-k", "Add provenance, freshness metadata, and pruning rules to memory", "Copy the old procedure into every prompt", "Disable all external memory"],
    correct_index: 1, correct_explanation: "Persistent memory needs lifecycle controls. Provenance and freshness allow stale items to be detected, while pruning or expiration removes them intentionally." },
  { title: "Evaluation — Select meaningful evaluation signals", primary_domain: 4, objective: "Select meaningful evaluation signals", difficulty: null,
    prompt: "A pull-request agent produces syntactically valid patches that often misunderstand the issue. Which evaluation set is most useful?",
    artifact_type: "code", artifact_content: JSON.stringify({ name: "evaluation.log", code: "build_passed=true\nsyntax_errors=0\nacceptance_criteria_checked=false\nreview_findings=7\nrollback_within_24h=true" }),
    options: ["Token count and response length only", "Issue acceptance criteria, relevant test outcomes, review findings, and rollback rate", "Number of comments in the pull request", "Average branch-name length"],
    correct_index: 1, correct_explanation: "Evaluation must connect development intent with quality and operational outcomes. Cost metrics can supplement—but cannot replace—correctness and reliability signals." },
  { title: "Evaluation — Classify root causes", primary_domain: 4, objective: "Classify root causes", difficulty: null,
    prompt: "An agent chose the right remediation but called a production tool with a malformed parameter. Logs show its reasoning and retrieved context were correct. How should the failure be classified?",
    artifact_type: null, artifact_content: null,
    options: ["Reasoning failure", "Tool misuse or interface failure", "Memory drift", "Multi-agent conflict"],
    correct_index: 1, correct_explanation: "The decision was correct and context was sound; the failure occurred at tool invocation. Correct classification prevents unnecessary prompt or memory changes." },
  { title: "Evaluation — Tune from evidence", primary_domain: 4, objective: "Tune from evidence", difficulty: null,
    prompt: "Evaluation traces show an agent succeeds until retrieved documents exceed the context budget, after which it ignores the latest policy. What is the best tuning move?",
    artifact_type: null, artifact_content: null,
    options: ["Make the system prompt longer", "Improve retrieval filtering and context prioritization, then rerun the evaluation", "Increase agent autonomy", "Add more unrelated examples"],
    correct_index: 1, correct_explanation: "The evidence identifies context overload. Selective retrieval and prioritization address that root cause; additional prompt content would worsen it." },
  { title: "Multi-agent — Isolate parallel execution", primary_domain: 5, objective: "Isolate parallel execution", difficulty: null,
    prompt: "Two agents work on independent issues but both modify the same workflow file in a shared checkout. Conflicts appear late and waste both runs. What should change?",
    artifact_type: "code", artifact_content: JSON.stringify({ name: "orchestrator.yml", code: "agents: [security-fix, dependency-fix]\nworkspace: /tmp/shared\nbranch: main\nfile_ownership_check: false" }),
    options: ["Give both agents the same branch so they see changes sooner", "Use isolated branches/workspaces and detect overlapping file ownership before execution", "Let the faster agent overwrite the slower one", "Disable all parallel work"],
    correct_index: 1, correct_explanation: "Parallel agents need isolated execution plus early conflict detection. This preserves concurrency while making overlapping ownership explicit." },
  { title: "Multi-agent — Document handoffs", primary_domain: 5, objective: "Document handoffs", difficulty: null,
    prompt: "A planning agent hands work to an implementation agent, which repeatedly revisits already-rejected designs. What artifact should the handoff include?",
    artifact_type: null, artifact_content: null,
    options: ["Only the final task title", "Structured decisions, constraints, rejected alternatives, acceptance criteria, and current state", "The planner's entire unfiltered conversation", "A request to start from scratch"],
    correct_index: 1, correct_explanation: "A concise, durable handoff prevents duplicated reasoning and contradictory outputs while avoiding the noise and stale material of a full transcript." },
  { title: "Multi-agent — Recover degraded workflows", primary_domain: 5, objective: "Recover degraded workflows", difficulty: null,
    prompt: "In a three-agent pipeline, the reviewer stalls while the implementer continues opening new changes. What is the safest recovery pattern?",
    artifact_type: null, artifact_content: null,
    options: ["Allow unlimited pending reviews", "Pause dependent work, preserve artifacts, retry or replace the reviewer, then escalate if the threshold is exceeded", "Delete all branches and restart immediately", "Ask the implementer to approve its own work"],
    correct_index: 1, correct_explanation: "Recovery should contain downstream impact, preserve evidence, attempt bounded recovery, and retain a human escalation path." },
  { title: "Guardrails — Right-size human intervention", primary_domain: 6, objective: "Right-size human intervention", difficulty: null,
    prompt: "A maintenance agent can format code, rotate production secrets, and delete cloud resources. Which autonomy policy is best?",
    artifact_type: "code", artifact_content: JSON.stringify({ name: "guardrails.yml", code: "actions:\n  format_code: auto\n  rotate_prod_secret: auto\n  delete_cloud_resource: auto\naudit_log: true" }),
    options: ["Require approval for every action", "Allow all actions because logs exist", "Auto-approve reversible formatting; require explicit authorization for secrets and destructive infrastructure actions", "Block the agent from formatting code"],
    correct_index: 2, correct_explanation: "Autonomy should be proportional to risk. Low-risk reversible work can stay fast, while security-sensitive or irreversible actions require explicit control." },
  { title: "Guardrails — Enforce controlled execution paths", primary_domain: 6, objective: "Enforce controlled execution paths", difficulty: null,
    prompt: "An agent identifies a critical production fix at 2 a.m. Company policy requires two-person approval for production changes. What should happen?",
    artifact_type: null, artifact_content: null,
    options: ["The agent bypasses policy because severity is critical", "The agent prepares the patch and evidence, then waits in the controlled approval path", "The agent uses a personal token to deploy", "The agent edits the audit log to mark approval"],
    correct_index: 1, correct_explanation: "Urgency does not remove compliance requirements. The agent can accelerate preparation and evidence while the protected production path enforces authorization." },
  { title: "Guardrails — Preserve accountability", primary_domain: 6, objective: "Preserve accountability", difficulty: null,
    prompt: "A team uses one shared service identity for five agents, making it impossible to attribute destructive actions. Which change best restores accountability?",
    artifact_type: null, artifact_content: null,
    options: ["Give every agent the shared password", "Use distinct workload identities and immutable action logs", "Store the shared token in a more secure vault", "Ask agents to include their names in commit messages"],
    correct_index: 1, correct_explanation: "Distinct identities provide reliable attribution; immutable logs preserve the record. A protected shared credential is still unable to distinguish actors." }
].map(item => ({ ...item, distractor_explanations: {}, decision_principle: null, source_links: [], published: true, review_status: "published", version: 1 }));
